import { useState } from 'react';
import { CheckCircle2, Database, Play, Plus, Save, Trash2 } from 'lucide-react';
import { api } from '../services/api';

type EditorKey = 'departments' | 'sections' | 'courses' | 'faculty' | 'allocations' | 'rooms' | 'laboratories' | 'batches' | 'availability' | 'constraints';
type Row = Record<string, string | number | boolean>;

const definitions: Array<{ key: EditorKey; title: string; description: string; fields: Array<{ key: string; label: string; type?: 'number' | 'checkbox' }> }> = [
    { key: 'departments', title: 'Departments', description: 'Department code and name.', fields: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }] },
    { key: 'sections', title: 'Sections', description: 'Department, year, semester, section, strength, block, advisor.', fields: [{ key: 'department', label: 'Department' }, { key: 'year', label: 'Year' }, { key: 'semester', label: 'Semester' }, { key: 'name', label: 'Section' }, { key: 'strength', label: 'Strength', type: 'number' }, { key: 'block', label: 'Block' }, { key: 'advisor', label: 'Advisor' }] },
    { key: 'courses', title: 'Courses', description: 'Use THEORY or LAB for course type.', fields: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'department', label: 'Department' }, { key: 'year', label: 'Year' }, { key: 'semester', label: 'Semester' }, { key: 'type', label: 'Type' }, { key: 'periodsPerWeek', label: 'Periods/week', type: 'number' }] },
    { key: 'faculty', title: 'Faculty', description: 'Faculty identity and workload.', fields: [{ key: 'id', label: 'Faculty ID' }, { key: 'name', label: 'Name' }, { key: 'department', label: 'Department' }, { key: 'designation', label: 'Designation' }, { key: 'weeklyWorkload', label: 'Weekly workload', type: 'number' }] },
    { key: 'allocations', title: 'Course Allocation', description: 'Connect faculty, course, and section.', fields: [{ key: 'facultyId', label: 'Faculty ID' }, { key: 'courseCode', label: 'Course code' }, { key: 'sectionName', label: 'Section' }] },
    { key: 'rooms', title: 'Rooms', description: 'Room capacity and availability.', fields: [{ key: 'block', label: 'Block' }, { key: 'name', label: 'Room' }, { key: 'floor', label: 'Floor' }, { key: 'capacity', label: 'Capacity', type: 'number' }, { key: 'department', label: 'Department' }, { key: 'active', label: 'Active', type: 'checkbox' }] },
    { key: 'laboratories', title: 'Laboratories', description: 'Lab capacity, type, and equipment.', fields: [{ key: 'name', label: 'Name' }, { key: 'block', label: 'Block' }, { key: 'floor', label: 'Floor' }, { key: 'capacity', label: 'Capacity', type: 'number' }, { key: 'type', label: 'Type' }, { key: 'equipment', label: 'Equipment' }] },
    { key: 'batches', title: 'Laboratory Batches', description: 'Batch name and student count.', fields: [{ key: 'sectionName', label: 'Section' }, { key: 'name', label: 'Batch' }, { key: 'studentCount', label: 'Students', type: 'number' }] },
    { key: 'availability', title: 'Faculty Availability', description: 'Uncheck Available to block a faculty slot.', fields: [{ key: 'facultyId', label: 'Faculty ID' }, { key: 'day', label: 'Day' }, { key: 'period', label: 'Period', type: 'number' }, { key: 'available', label: 'Available', type: 'checkbox' }, { key: 'preferred', label: 'Preferred', type: 'checkbox' }] },
    { key: 'constraints', title: 'Institutional Constraints', description: 'Optional rules passed to the saved dataset.', fields: [{ key: 'name', label: 'Rule name' }, { key: 'enabled', label: 'Enabled', type: 'checkbox' }, { key: 'value', label: 'Value' }] },
];

const blankRow = (fields: Array<{ key: string; type?: 'number' | 'checkbox' }>): Row => Object.fromEntries(fields.map(({ key, type }) => [key, type === 'checkbox' ? true : type === 'number' ? 1 : '']));

export function TimetableInputPage() {
    const [name, setName] = useState('My College Timetable');
    const [academicYear, setAcademicYear] = useState('2026-2027');
    const [semester, setSemester] = useState('Semester 1');
    const [workingDays, setWorkingDays] = useState([{ name: 'Monday', periods: 6, startTime: '09:00', endTime: '15:10' }]);
    const [records, setRecords] = useState<Record<EditorKey, Row[]>>(() => Object.fromEntries(definitions.map(({ key, fields }) => [key, [blankRow(fields)]])) as Record<EditorKey, Row[]>);
    const [datasetId, setDatasetId] = useState<string | null>(null);
    const [result, setResult] = useState<any | null>(null);
    const [message, setMessage] = useState<string | null>(null);
    const [isSaving, setIsSaving] = useState(false);

    const updateRow = (key: EditorKey, index: number, field: string, value: string | number | boolean) => setRecords((current) => ({ ...current, [key]: current[key].map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row) }));
    const addRow = (key: EditorKey, fields: Array<{ key: string; type?: 'number' | 'checkbox' }>) => setRecords((current) => ({ ...current, [key]: [...current[key], blankRow(fields)] }));
    const removeRow = (key: EditorKey, index: number) => setRecords((current) => ({ ...current, [key]: current[key].filter((_, rowIndex) => rowIndex !== index) }));
    const cleanRows = (rows: Row[]) => rows.filter((row) => Object.entries(row).some(([key, value]) => key === 'active' || key === 'available' || key === 'preferred' || String(value).trim() !== '')).map((row) => row);
    const buildPayload = () => ({ name, academicYear, semester, workingDays, ...Object.fromEntries(definitions.map(({ key }) => [key, cleanRows(records[key])])) });

    const save = async () => { setIsSaving(true); setMessage(null); try { const saved = await api.saveTimetableInput(buildPayload()); setDatasetId(saved.id); setMessage(`Saved dataset "${saved.name}". Existing sample data remains unchanged.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save timetable input.'); } finally { setIsSaving(false); } };
    const generate = async () => { setIsSaving(true); setMessage(null); try { const saved = datasetId ? { id: datasetId } : await api.saveTimetableInput(buildPayload()); setDatasetId(saved.id); const generated = await api.generateTimetableInput(saved.id); setResult(generated); setMessage(`Generated ${generated.generatedEntries} sessions from the entered data.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to generate timetable.'); } finally { setIsSaving(false); } };

    return <div className="space-y-6">
        <div className="card p-5"><div className="text-sm font-semibold uppercase tracking-[0.24em] text-sky-700">Create Timetable</div><div className="mt-1 text-2xl font-bold text-slate-800">Timetable input workspace</div><div className="mt-2 text-sm text-slate-500">Enter normal college records and generate a separate timetable dataset.</div></div>
        <div className="card p-5"><div className="mb-4 flex items-center gap-2"><Database className="h-5 w-5 text-sky-700" /><div className="text-lg font-bold text-slate-800">College and academic setup</div></div><div className="grid gap-3 md:grid-cols-3"><label className="text-sm text-slate-600">Dataset name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-xl border border-sky-100 px-3 py-2" /></label><label className="text-sm text-slate-600">Academic year<input value={academicYear} onChange={(event) => setAcademicYear(event.target.value)} className="mt-1 w-full rounded-xl border border-sky-100 px-3 py-2" /></label><label className="text-sm text-slate-600">Semester<input value={semester} onChange={(event) => setSemester(event.target.value)} className="mt-1 w-full rounded-xl border border-sky-100 px-3 py-2" /></label></div><div className="mt-4 space-y-2"><div className="text-sm font-semibold text-slate-700">Working days and periods</div>{workingDays.map((day, index) => <div key={index} className="grid gap-2 md:grid-cols-4"><input value={day.name} onChange={(event) => setWorkingDays((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))} placeholder="Day" className="rounded-xl border border-sky-100 px-3 py-2 text-sm" /><input type="number" min="1" value={day.periods} onChange={(event) => setWorkingDays((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, periods: Number(event.target.value) } : item))} placeholder="Periods" className="rounded-xl border border-sky-100 px-3 py-2 text-sm" /><input value={day.startTime} onChange={(event) => setWorkingDays((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, startTime: event.target.value } : item))} placeholder="Start" className="rounded-xl border border-sky-100 px-3 py-2 text-sm" /><input value={day.endTime} onChange={(event) => setWorkingDays((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, endTime: event.target.value } : item))} placeholder="End" className="rounded-xl border border-sky-100 px-3 py-2 text-sm" /></div>)}<button type="button" onClick={() => setWorkingDays((items) => [...items, { name: '', periods: 6, startTime: '09:00', endTime: '15:10' }])} className="inline-flex items-center gap-1 text-sm font-semibold text-sky-700"><Plus className="h-4 w-4" /> Add working day</button></div></div>
        <div className="grid gap-6 xl:grid-cols-2">{definitions.map(({ key, title, description, fields }) => <div key={key} className="card p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-lg font-bold text-slate-800">{title}</div><div className="mt-1 text-sm text-slate-500">{description}</div></div><button type="button" onClick={() => addRow(key, fields)} className="inline-flex items-center gap-1 rounded-lg border border-sky-200 px-2 py-1 text-xs font-semibold text-sky-700"><Plus className="h-3 w-3" /> Add</button></div><div className="mt-4 space-y-3">{records[key].map((row, index) => <div key={index} className="rounded-xl border border-sky-100 bg-slate-50 p-3"><div className="grid gap-2 sm:grid-cols-2">{fields.map((field) => field.type === 'checkbox' ? <label key={field.key} className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={Boolean(row[field.key])} onChange={(event) => updateRow(key, index, field.key, event.target.checked)} />{field.label}</label> : <label key={field.key} className="text-xs text-slate-500">{field.label}<input type={field.type === 'number' ? 'number' : 'text'} value={String(row[field.key] ?? '')} onChange={(event) => updateRow(key, index, field.key, field.type === 'number' ? Number(event.target.value) : event.target.value)} className="mt-1 w-full rounded-lg border border-sky-100 bg-white px-2 py-1.5 text-sm text-slate-800" /></label>)}</div>{records[key].length > 1 && <button type="button" onClick={() => removeRow(key, index)} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-rose-600"><Trash2 className="h-3 w-3" /> Remove</button>}</div>)}</div></div>)}</div>
        {message && <div className="card border-sky-200 bg-sky-50 p-4 text-sm text-slate-700">{message}</div>}
        <div className="sticky bottom-4 flex flex-wrap gap-3 rounded-2xl border border-sky-100 bg-white/95 p-4 shadow-lg"><button type="button" disabled={isSaving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-xl border border-sky-200 bg-white px-5 py-3 text-sm font-semibold text-sky-700 disabled:opacity-50"><Save className="h-4 w-4" /> Save Input</button><button type="button" disabled={isSaving} onClick={() => void generate()} className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50"><Play className="h-4 w-4" /> Generate Timetable</button>{result && <span className="inline-flex items-center gap-2 px-3 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" /> {result.generatedEntries} sessions generated for {result.sections} sections</span>}</div>
        {result && <div className="card p-5"><div className="text-lg font-bold text-slate-800">Generated timetable preview</div><div className="mt-4 overflow-auto"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-sky-50"><tr><th className="px-3 py-2">Section</th><th className="px-3 py-2">Course</th><th className="px-3 py-2">Faculty</th><th className="px-3 py-2">Day</th><th className="px-3 py-2">Period</th><th className="px-3 py-2">Room/Lab</th></tr></thead><tbody>{result.timetable.map((entry: any, index: number) => <tr key={index} className="border-t border-sky-100"><td className="px-3 py-2">{entry.section}</td><td className="px-3 py-2">{entry.course}</td><td className="px-3 py-2">{entry.faculty}</td><td className="px-3 py-2">{entry.day}</td><td className="px-3 py-2">P{entry.period}</td><td className="px-3 py-2">{entry.room ?? entry.laboratory ?? '—'}</td></tr>)}</tbody></table></div></div>}
    </div>;
}
