import { env } from '../config/env.js';

type ReasoningResult = {
    status: 'completed' | 'unavailable';
    model: string;
    explanation: string;
    decisions: string[];
    unscheduled: string[];
};

const fallback = (message: string): ReasoningResult => ({
    status: 'unavailable',
    model: env.geminiModel,
    explanation: message,
    decisions: [],
    unscheduled: [],
});

export async function reviewGeneratedTimetable(input: unknown, generated: unknown, failures: string[] = []): Promise<ReasoningResult> {
    if (!env.geminiApiKey) return fallback('LLM reasoning is unavailable because GEMINI_API_KEY is not configured. Deterministic constraint validation remains authoritative.');

    const prompt = `You are reviewing a timetable that was already generated by a deterministic constraint solver. You are not the solver and must not create, move, delete, or invent any placement. Analyze only the supplied submitted input and generated schedule. Explain important valid decisions, identify any unscheduled items already listed, and mention hard-constraint concerns only when visible in the supplied data. Return strict JSON with exactly these keys: explanation (string), decisions (array of strings), unscheduled (array of strings). Never expose database IDs.\n\nSUBMITTED INPUT:\n${JSON.stringify(input)}\n\nGENERATED SCHEDULE:\n${JSON.stringify(generated)}\n\nKNOWN UNSCHEDULED ITEMS:\n${JSON.stringify(failures)}`;
    const models = Array.from(new Set([env.geminiModel, 'gemini-3.6-flash', 'gemini-2.5-flash'].filter(Boolean)));
    let lastError = 'Gemini reasoning request failed.';

    for (const model of models) {
        try {
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${env.geminiApiKey}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    generationConfig: { temperature: 0.1, responseMimeType: 'application/json' },
                    contents: [{ role: 'user', parts: [{ text: prompt }] }],
                }),
            });
            if (!response.ok) {
                lastError = `Gemini reasoning failed (${response.status}).`;
                continue;
            }
            const data = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
            const text = data.candidates?.flatMap((candidate) => candidate.content?.parts ?? []).map((part) => part.text ?? '').join('').trim();
            if (!text) {
                lastError = 'Gemini reasoning returned an empty response.';
                continue;
            }
            const parsed = JSON.parse(text) as { explanation?: unknown; decisions?: unknown; unscheduled?: unknown };
            return {
                status: 'completed',
                model,
                explanation: typeof parsed.explanation === 'string' ? parsed.explanation : 'The generated schedule passed through deterministic validation.',
                decisions: Array.isArray(parsed.decisions) ? parsed.decisions.filter((item): item is string => typeof item === 'string') : [],
                unscheduled: Array.isArray(parsed.unscheduled) ? parsed.unscheduled.filter((item): item is string => typeof item === 'string') : failures,
            };
        } catch (error) {
            lastError = error instanceof Error ? error.message : lastError;
        }
    }

    return fallback(`${lastError} Deterministic constraint validation remains authoritative; no generated placement was changed.`);
}
